[package]
name = "retoco-proc-macro"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
retoco-token-stream = { path = "../retoco-token-stream" }
iex = "0.2"
