[package]
name = "retoco-token-stream"
version.workspace = true
edition.workspace = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
regex-syntax = "0.8.4"
syn = "2.0.77"
thiserror = "1.0.63"
